version: "3"

services:
  sql-server:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sql-server-2019
    environment:
      sa_password: Admin1234
      ACCEPT_EULA: Y
    ports:
      - 14333:1433
    volumes:
      - ./data:/var/opt/mssql/data